### ISSUE TITLE
High latency when using

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#58] opened 2022-02-02 03:35 UTC
At first I thought it wasn't newm, but after carefully analyzing it I realized that what it puts on the screen has a lot of latency and it only happens to who I already tried with swaywm

**Comment by jbuchermn** [comment] 2022-02-02 07:22
Can you be more specific, where the latency happens?
A
- Are there slow animations?
- Is interacting with apps slow?


Which commit are you on? I'm trying to bring down idle cpu which on some commits has had implications on animations..

**Comment by CRAG666** [comment] 2022-02-02 13:04
ironically the animations work well, the latency occurs with the applications, for example when I write I have to do modpress to update the screen

**Comment by CRAG666** [comment] 2022-02-02 13:06
so far it happens with all the applications even with the terminal kitty

**Comment by CRAG666** [comment] 2022-02-02 13:07
@jbuchermn I'm currently on the newest commit

**Comment by jbuchermn** [comment] 2022-02-02 13:34
Ah that does sound like damaging issues. Can you test older commits, when did this start?

Does it work when using a single output?

Does it work if you add

```
pywm = { 'renderer_mode' = 'passthrough'}
```

Or with direct instead of passthrough?

**Comment by CRAG666** [comment] 2022-02-02 13:42
This last one I have not tried it I will try with that. I will do regressions to confirm at what point the error is, even though I think it was 2 commits ago when there were significant changes, because the last commit was minor changes

**Comment by CRAG666** [comment] 2022-02-02 13:47
What is the difference between direct and passthrough

**Comment by CRAG666** [comment] 2022-02-02 13:53
@jbuchermn It doesn't work when I use these options 'passthrough or direct

**Comment by CRAG666** [comment] 2022-02-02 13:54
The behavior is the same if I use a single output

**Comment by jbuchermn** [comment] 2022-02-02 13:54
Passthrough is wlroots renderer, without any effects. Direct is basically the old implementation, indirect (default) is the new one, which can blur.

I've tested all three quite extensively on my MacBook, but never with a second monitor, as I don't use one, so I suspect that is the issue.

**Comment by jbuchermn** [comment] 2022-02-02 13:55
Can you confirm that the windows do not redraw, until you trigger an animation?

Is this only related to kitty?

**Comment by CRAG666** [comment] 2022-02-02 13:58
The behavior is as follows for any application, when trying to write or scroll for example, the screen simply remains static until I do modpress or move from window, the window is updated

**Comment by CRAG666** [comment] 2022-02-02 14:06
This pywm commit is the last one without this 608e4f6 error

**Comment by jbuchermn** [comment] 2022-02-02 17:26
> The behavior is as follows for any application, when trying to write or scroll for example, the screen simply remains static until I do modpress or move from window, the window is updated

Okay, that's most certainly an issue with damage tracking.



> This pywm commit is the last one without this 608e4f6 error

Interesting, this is actually a commit already using the new renderer. Checking out pywm to this commit makes it work?

**Comment by jbuchermn** [comment] 2022-02-02 17:40
Can you upload a log?

**Comment by CRAG666** [comment] 2022-02-02 17:48
Is there a way to find out which configuration is failing, as I keep up with updates I have no idea what the configuration is failing,

**Comment by jbuchermn** [comment] 2022-02-02 17:50
I don't think that's a configuration issue. It's a bug.

**Comment by CRAG666** [comment] 2022-02-02 17:50
> Can you upload a log?
Of course I will upload the record that I have now with the regression and I will upload the record with the current commit

**Comment by CRAG666** [comment] 2022-02-02 17:54
I would also like to know if I add any additional dependencies, one that is not registered in the README or in pkbuild of arch

**Comment by CRAG666** [comment] 2022-02-02 18:05
https://drive.google.com/file/d/1ggPGmyq8hodxA76yActo4SJGigtneCkJ/view?usp=sharing
This is log using the current commit

**Comment by CRAG666** [comment] 2022-02-03 21:37
@jbuchermn  I found these lines in your nix config, does it have something to do with new updates, why don't they matter? I see that they are only there but they are not imported and they are not variables either:
    'c': PLACEHOLDER_c_gestures,
    'pyevdev': PLACEHOLDER_pyevdev_gestures,

**Comment by CRAG666** [comment] 2022-02-03 23:41
@jbuchermn I think I'm already getting to the possible problem.
When recording a video where I wanted to show the latency the latency disappears when using the record command, however the moment I stop using the command to record the latency reappears.
In the video I show the newm log in real time.
I have some doubts about it. For example, does it affect the use of the iHD driver (it is the recommended driver for Intel video cards)? And on the other hand, does newm currently use hardware acceleration?
https://drive.google.com/file/d/1X87NCw5OGgAcNKLTi8OyhYPnjoS7ZuLO/view?usp=sharing
The command I use to record video is the following, it may help to solve the problem:
```bash
wf-recorder -f test-vaapi2.mkv -d /dev/dri/card0
```

**Comment by CRAG666** [comment] 2022-02-03 23:44
This is the constant output in logs when recording the screen:
00:15:12.325 [DEBUG] [types/output/render.c:236] Enabling direct scan-out on output 'eDP-1' (locks: 0)
00:15:12.325 [DEBUG] [types/output/cursor.c:43] Enabling hardware cursors on output 'eDP-1' (locks: 0)
00:15:12.325 [DEBUG] [types/output/render.c:236] Disabling direct scan-out on output 'eDP-1' (locks: 1)
00:15:12.325 [DEBUG] [types/output/cursor.c:43] Disabling hardware cursors on output 'eDP-1' (locks: 1)

**Comment by CRAG666** [comment] 2022-02-03 23:49
This is the output when I don't use the record command
(nm-applet:1587): Gtk-CRITICAL **: 17:47:09.933: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
00:20:06.010 [DEBUG] [../src/wm/wm.c:158] 
TIMER[callback_key                  ]  :    0.09ms (   0.14ms max),  1.60Hz
[DEBUG] layout.py:727 2022-02-03 17:47:10: Resetting gesture
00:20:06.010 [DEBUG] [../src/wm/wm.c:169] 
TIMER[callback_modifiers            ]  :    0.04ms (   0.15ms max),  0.40Hz
[DEBUG] layout.py:235 2022-02-03 17:47:10: Queuing animation
[DEBUG] layout.py:253 2022-02-03 17:47:10: Thread: Starting animation...
00:20:06.278 [DEBUG] [../src/wm/wm_output.c:139] 
TIMER[render                        ]  :    0.25ms (   0.55ms max),  2.20Hz
00:20:06.292 [DEBUG] [../src/wm/wm_server.c:560] 
TIMER[between_schedule_callback     ] X:  632.01ms (11836.90ms max),  2.20Hz
[DEBUG] layout.py:259 2022-02-03 17:47:10: Thread: Finishing animation...
[DEBUG] layout.py:727 2022-02-03 17:47:10: Resetting gesture
[DEBUG] layout.py:235 2022-02-03 17:47:10: Queuing animation
[DEBUG] layout.py:253 2022-02-03 17:47:10: Thread: Starting animation...
[DEBUG] layout.py:259 2022-02-03 17:47:11: Thread: Finishing animation...
00:20:07.967 [DEBUG] [../src/wm/wm.c:180] 
TIMER[callback_motion               ]  :    0.12ms (   0.27ms max),  7.90Hz
[DEBUG] layout.py:800 2022-02-03 17:47:11: Gesture SingleFingerMove...
00:20:08.807 [DEBUG] [../src/wm/wm.c:192] 
TIMER[callback_button               ]  :    0.07ms (   0.10ms max),  0.20Hz

**Comment by jbuchermn** [comment] 2022-02-04 14:28
The fact, that it works when recording, is very interesting. This points at another direction than damage tracking; however I'm still a bit unsure what the issue is.



> @jbuchermn I think I'm already getting to the possible problem. When recording a video where I wanted to show the latency the latency disappears when using the record command, however the moment I stop using the command to record the latency reappears. In the video I show the newm log in real time. I have some doubts about it. For example, does it affect the use of the iHD driver (it is the recommended driver for Intel video cards)? And on the other hand, does newm currently use hardware acceleration? https://drive.google.com/file/d/1X87NCw5OGgAcNKLTi8OyhYPnjoS7ZuLO/view?usp=sharing The command I use to record video is the following, it may help to solve the problem:
> 
> ```shell
> wf-recorder -f test-vaapi2.mkv -d /dev/dri/card0
> ```

newm uses OpenGL ES 3.2 (or 2.0 if using direct or passthrough rendering). This is basically the same as sway and hasn't really changed. So yes, it's hardware accelerated.

Can you confirm that pywm commit https://github.com/jbuchermn/pywm/commit/608e4f6594776c8a39bf4b20e89263f7551c5447 works, and https://github.com/jbuchermn/pywm/commit/6432006544ac3f784b03d9fc1a98d7ff921ef049 doesn't?

**Comment by CRAG666** [comment] 2022-02-04 15:56
@jbuchermn the latency still exists in the new commit, and as I said in the previous message it only disappears when I use the wf-recorder command

**Comment by CRAG666** [comment] 2022-02-04 15:58
Regarding the previous commit, yesterday I also did tests, the latency is lower in that commit, it is hardly noticeable except in some cases, for example when I scroll through vim very quickly, the latency is present in the form of a pause that lasts a few seconds. it is much less than the current commit but latency is present

**Comment by jbuchermn** [comment] 2022-02-04 15:58
Yup the new commit doesn't change anything. The important part is

> Can you confirm that pywm commit [jbuchermn/pywm@608e4f6](https://github.com/jbuchermn/pywm/commit/608e4f6594776c8a39bf4b20e89263f7551c5447) works, and [jbuchermn/pywm@6432006](https://github.com/jbuchermn/pywm/commit/6432006544ac3f784b03d9fc1a98d7ff921ef049) doesn't?

Because, if that is confirmed, I can focus on comparing these two commits.

**Comment by jbuchermn** [comment] 2022-02-04 16:00
> Regarding the previous commit, yesterday I also did tests, the latency is lower in that commit, it is hardly noticeable except in some cases, for example when I scroll through vim very quickly, the latency is present in the form of a pause that lasts a few seconds. it is much less than the current commit but latency is present

Ah okay, that is very important. Can you please go back further and check which commit is the last one to actually work completely?

Also, the latency is also present in `passthrough` mode, right? Can you confirm, that corners are not round in `passthrough` mode?

**Comment by CRAG666** [comment] 2022-02-04 16:10
i tried with this:
```python
pywm = {
    'renderer_mode': 'passthrough',
    'xkb_model': "PLACEHOLDER_xkb_model",
    'xkb_layout': "es",
    'xkb_options': "caps:swapescape",
    'encourage_csd': False,
    'enable_xwayland': True,
    'natural_scroll': True,
    # 'texture_shaders': 'basic',
    'focus_follows_mouse': True,
    'xcursor_theme': 'Sweet-cursors',
    'xcursor_size': 24,
    # 'contstrain_popups_to_toplevel': True
}
```
Corners are not rounded in this mode and latency still exists

**Comment by jbuchermn** [comment] 2022-02-04 16:56
okay, thanks a lot. That is important.

I don't really know where to look at the moment. Are you experiencing any other issues? E.g., do YouTube videos play properly? Is the cursor lagging?

**Comment by CRAG666** [comment] 2022-02-04 17:47
It is curious because the animations are very fluid even more than before, the problem is scrolling or writing is where the latency appears.

**Comment by CRAG666** [comment] 2022-02-04 17:49
Modpress works fine in fact I have to be doing Modpress for the screen to update. modpress works great

**Comment by jbuchermn** [comment] 2022-02-04 18:39
Thats very curious indeed. Maybe the bug isn't so much related to damage tracking, but to frame scheduling.

Can you please
1. Open kitty and a browser side by side so both are visible
2. Start a YouTube video in the browser
3. Start typing inside kitty

Does the video play back properly?
Do you need to hit ModPress for typed text to be visible?

**Comment by CRAG666** [comment] 2022-02-04 19:06
The video is delayed and sometimes the image is paused but the audio is still heard. When I type or scroll the latency keeps showing up (kitty or vim). I have to Modpress for the image to update

**Comment by CRAG666** [comment] 2022-02-04 19:11
Modpress forces to update the screen, this also applies to animations, I use three fingers to move and the screen is updated. It is quite strange that the animations work extremely smooth even more than in version two, but the screen when typing or scrolling or watching videos freezes and only until I move with the touchpad or press modpress does it update

**Comment by CRAG666** [comment] 2022-02-04 19:13
@jbuchermn Also it is still not clear to me why while using wf-recorder newm works without latency. It's strange, could it have something to do with my graphics card "/dev/dri/card0"? because when I record I use hardware acceleration.

**Comment by jbuchermn** [comment] 2022-02-04 19:38
> The video is delayed and sometimes the image is paused but the audio is still heard. When I type or scroll the latency keeps showing up (kitty or vim). I press Modpress for the image to update

Okay, probably the updates occur simulataneously? I.e. while the window is delayed, also kitty is delayed.



> @jbuchermn Also it is still not clear to me why while using wf-recorder newm works without latency. It's strange, could it have something to do with my graphics card "/dev/dri/card0"? because when I record I use hardware acceleration.

Actually when you record you lose a lot of hw acceleration and gain no acceleration (e.g. hardware cursors).

It's not an issue of latency, but on redraw events not being triggered when necessary. To be more clear, the screen is only rendered when needed - either because a window updates content, or because a window is moved. The second situation works properly, but in the first one, the necessary redraw event is lost somewhere inside pywm, which means the updated windows are not rendered and your video pauses. Once the second situation comes into play (you hit ModPress, use a gesture, ...) the updates become visible.

It's quite hard to find the reason for this issue... Can you post your output config?

**Comment by CRAG666** [comment] 2022-02-05 01:10
Sure, it's pretty simple
outputs = [
    {'name': 'eDP-1', 'scale': 0.6},
    {'name': 'DP-2', 'scale': 0.6},
]
Here I use fractional scale but I have tried with scale 1, 2 and using a single monitor and the latency continues

**Comment by jbuchermn** [comment] 2022-02-05 08:48
Okay nothing special there...

I think, we need to debug this. I created a branch `debug` on pywm. Can you check out this branch and run it (with `start-newm --debug`) and send me a log file? Please run newm only for a short time, as the debug branch produces a lot of output.

**Comment by CRAG666** [comment] 2022-02-05 22:36
https://drive.google.com/file/d/1hxzNDPmcfwF7M8QuVfyEzxQloIifIYUN/view?usp=sharing

**Comment by CRAG666** [comment] 2022-02-05 22:37
I already sent the log

**Comment by jbuchermn** [comment] 2022-02-06 09:13
Thank you for the log. Can you repeat with the current commit?

And can you maybe also start screen recording as a comparison?

**Comment by CRAG666** [comment] 2022-02-07 01:06
@jbuchermn incredible the debug branch of pywm is working, the latency disappeared, only that I noticed that the corners are not rounded, use direct and indirect with these two the corners are rounded, it can also be said that all renderer_mode work without latency, now the question what renderer_mode should i use?.

**Comment by CRAG666** [comment] 2022-02-07 01:08
newm_log https://drive.google.com/file/d/1v_6aPsWsceVYDWIpLH7Grow4WyZfNUc7/view?usp=sharing
In any case, send the log, maybe there is something that I am not seeing. But again amazing work, this works perfect, super smooth

**Comment by CRAG666** [comment] 2022-02-07 01:10
@jbuchermn Also notice that waybar does not start. But it's still a minor error but I'll notify you anyway

**Comment by jbuchermn** [comment] 2022-02-07 20:23
> @jbuchermn incredible the debug branch of pywm is working, the latency disappeared, only that I noticed that the corners are not rounded, use direct and indirect with these two the corners are rounded, it can also be said that all renderer_mode work without latency, now the question what renderer_mode should i use?.

That's great to hear. In general you'll want to use 'indirect' (only mode to support blur), 'direct' is a bit more efficient (less copying) and passthrough is basically only for testing (doesn't have rounded corners, blur, ...). I'll have to document all of this before v0.3 is released.

I just tried to merge the last changes into v0.3 - can you try if there are issues when using this branch?

**Comment by CRAG666** [comment] 2022-02-07 20:53
@jbuchermn I'm trying this right now

**Comment by CRAG666** [comment] 2022-02-08 01:12
@jbuchermn latency is still present on the v3 branch :(

**Comment by CRAG666** [comment] 2022-02-08 01:13
@jbuchermn the debug branch works without latency I'm already testing both branches 3 times

**Comment by jbuchermn** [comment] 2022-02-08 16:09
Okay that's quite interesting. Appears this was only lucky that it worked for a short time.

Can you please compare the last three commits on branch debug for all renderer_modes?

**Comment by jbuchermn** [comment] 2022-02-08 17:57
Okay, be careful though, the debug branch produces huge log files. Also you'll probably see artifacts on blurred windows..

**Comment by CRAG666** [comment] 2022-02-08 23:05
b8d8c10 It works without latency

**Comment by CRAG666** [comment] 2022-02-08 23:42
Traceback (most recent call last):
  File "/usr/bin/newm-cmd", line 3, in <module>
    from newm import cmd
  File "/usr/lib/python3.10/site-packages/newm/__init__.py", line 9, in <module>
    from .run import run
  File "/usr/lib/python3.10/site-packages/newm/run.py", line 5, in <module>
    from .layout import Layout
  File "/usr/lib/python3.10/site-packages/newm/layout.py", line 22, in <module>
    from pywm.touchpad import (
ModuleNotFoundError: No module named 'pywm.touchpad'
I have this error when trying the other commits and also with the newest commit

**Comment by CRAG666** [comment] 2022-02-09 02:13
The latency exists in this commit 1b5d9a4

**Comment by CRAG666** [comment] 2022-02-09 02:20
The latency exists in this commit https://github.com/jbuchermn/pywm/commit/a0342944f5236f5daf78b744894d9f1f2978e36b

**Comment by CRAG666** [comment] 2022-02-09 02:32
@jbuchermn  I leave you the screenshot of the packages that I compiled in arch linux of each of the commits
![package](https://i.ibb.co/529j6Dh/screen-1644373770.png)

**Comment by jbuchermn** [comment] 2022-02-09 12:18
Thanks for the tests. Unfortunately I still have very little idea, what the problem might be.

I just pushed another commit to the debug branch, which does not change rendering, but does output more log info.

Could you run that for a short time (until you see lag for the first time) and post a log file?

**Comment by CRAG666** [comment] 2022-02-09 15:14
> Thanks for the tests. Unfortunately I still have very little idea, what the problem might be.
> 
> I just pushed another commit to the debug branch, which does not change rendering, but does output more log info.
> 
> Could you run that for a short time (until you see lag for the first time) and post a log file?

shure

**Comment by jbuchermn** [comment] 2022-02-10 08:19
I did some more changes on the debug branch - can you please re-start and re-upload?

Also

- Do you experience lag when moving the cursor? I.e. does the cursor jump a lot?
- How big is the latency? Is it like 1/10th second, or multiple seconds, until you push the Mod key?

**Comment by jbuchermn** [comment] 2022-02-10 15:45
Yeah I'm changing a lot at the moment concerning timing. Current debug branch is wip.

I'll let you know once it's reached testable state. But it's good to see that the precious kind of latency is gone

**Comment by CRAG666** [comment] 2022-02-10 15:53
@jbuchermn yes, the latency disappears when I hit modpress. i so sorry, english is not my native language.

**Comment by CRAG666** [comment] 2022-02-10 16:00
@jbuchermn Describe the complete behavior:
I open vim and a browser when trying to scroll the latency appears then I press ModPress and the screen refreshes again I try to scroll and for about 30 or 20 seconds there is no latency until it appears again and again I press Modpress so the screen refreshes now yes on. On this occasion the animations are also slow unlike past commits where the latency existed but the animations were fluid. Also, at least in the tests I did, the latency did not appear while I was writing, something that happened in past commits.

**Comment by jbuchermn** [comment] 2022-02-10 19:15
I just pushed another commit to pywm debug (and correspondingly to newm debug). This still has a lot of issues as it changes most of how frame timing used to work. If you have time, I'd be interested in a log from on your machine.

> @jbuchermn Describe the complete behavior: I open vim and a browser when trying to scroll the latency appears then I press ModPress and the screen refreshes again I try to scroll and for about 30 or 20 seconds there is no latency until it appears again and again I press Modpress so the screen refreshes. On this occasion the animations are also slow unlike past commits where the latency existed but the animations were fluid. 

The current version output a lot of timing info into the log, so if you post one, I should be able to see where it's slow and where fast.

> Also, at least in the tests I did, the latency did not appear while I was writing, something that happened in past commits.

That's actually a really good thing - this part bugged me the most.

**Comment by DimitrisMilonopoulos** [comment] 2022-02-10 21:17
Same here, happened n firefox and kitty for me. I thought it was just latency but after some digging, I also came to the conclusion that the refresh seems to hand and `Mod` can retrigger it in a proper manner.

**Comment by CRAG666** [comment] 2022-02-10 22:30
@jbuchermn Is there a change in the configuration or is it the same as v3

**Comment by jbuchermn** [comment] 2022-02-10 22:32
You should be able to use the same config on the debug branch

**Comment by jbuchermn** [comment] 2022-02-10 22:40
I forgot to mention.. please use only one screen for the logs. It makes it easier for me to read...

**Comment by DimitrisMilonopoulos** [comment] 2022-02-10 22:47
> > Same here, happened n firefox and kitty for me. I thought it was just latency but after some digging, I also came to the conclusion that the refresh seems to hand and `Mod` can retrigger it in a proper manner.
> 
> That‘s an accurate assessment of what's (probably) happening.
> 
> Funny enough I haven't seen it on my laptop until now, but I see different bugs which may relate to the same thing... and I've started to reorganise a lot of code related to this. Which branch are you using?

V0.3 on newm and poc_blur on pywm

**Comment by CRAG666** [comment] 2022-02-10 22:56
log https://drive.google.com/file/d/1oEfjVFdl7CoMhhJAe5mNg3FrHlKFWpkO/view?usp=sharing

**Comment by CRAG666** [comment] 2022-02-10 22:59
@jbuchermn the debug branch (newm and pywm) still has echo latency, this time I returned the latency while writing. The animations are slow when using two monitors (the log I send is only with one monitor :))

**Comment by jbuchermn** [comment] 2022-02-11 07:25
> log https://drive.google.com/file/d/1oEfjVFdl7CoMhhJAe5mNg3FrHlKFWpkO/view?usp=sharing

Thanks. Theres a lo lot info in there, I'll have to go through it. 

> @jbuchermn the debug branch (newm and pywm) still has latency, in fact this time I returned the latency while writing. The animations are slow when using two monitors (the log I send is only with one monitor :))

Do animations and "echo latency" behave differently, when you're only on one screen?

**Comment by jbuchermn** [comment] 2022-02-12 13:20
Good news.. I'm finally able to partly reproduce the "echo lag" (at least sometimes).

I just pushed to debug; the last commit appears to fix echo lag for me. Can you try?

Note: For the performance issues regarding animations and gestures, I opened a separate issue (https://github.com/jbuchermn/newm/issues/61) to keep this one focused on the original bug.

**Comment by CRAG666** [comment] 2022-02-12 15:38
Understood I find it better to focus on one thing at a time. Do you need the log of these new changes?

**Comment by jbuchermn** [comment] 2022-02-12 15:49
Just let me know if there is any different behaviour. I'll then add the necessary debug statements in the next step.

**Comment by CRAG666** [comment] 2022-02-12 15:53
@jbuchermn You are amazing. This works without latency. I really thank you very much. there are still some problems but nothing to do with this issue. Officially the debug branch works without latency

**Comment by CRAG666** [comment] 2022-02-12 16:06
@jbuchermn Does the v3 branch have these changes? I ask so that I go to v3 and test that branch

**Comment by jbuchermn** [comment] 2022-02-12 16:09
I'm glad this finally seems to be resolved. I'll close the issue for now and we'll focus on the performance issues in #61.

v0.3 and debug right now are basically identical, only debug produces very big (and informative) logs.

**Closed** 2022-02-12 16:10 UTC
Labels: bug
