### ISSUE TITLE
Status for multi-monitor setups

### ISSUE THREAD

**Issue by cristiioan** [jbuchermn/newm#4] opened 2021-10-26 05:56 UTC
I'm thinking of using your project but I need to know if I can use multi-monitor setups(Laptop + External Display).

**Comment by CRAG666** [comment] 2021-11-11 20:50
This works perfect, better than I expected, only that it would be great ModPress to detect which monitor you are currently on

**Comment by jbuchermn** [comment] 2021-11-15 14:40
I added the individual overview (per monitor) to the backlog. That's probably a good feature :)

**Comment by jbuchermn** [comment] 2021-11-24 16:54
This is now possible via

```    
("ModPress", lambda: layout.toggle_overview(only_active_workspace=True)),
```

**Comment by CRAG666** [comment] 2021-11-24 20:02
thanks, awesome

**Comment by CRAG666** [comment] 2021-11-24 20:04
@jbuchermn  now only one command is missing to move between monitors without using the mouse

**Comment by jbuchermn** [comment] 2021-11-24 20:17
Try

```
("M-w", lambda: layout.change_focused_view_workspace()),
```

**Comment by CRAG666** [comment] 2021-12-03 22:57
This behavior only occurs when there are two monitors.
When I try to see the nm-applet options among other elements of the tray they are not shown offset in a different position than where the element of the tray is.
now if I do the same on the secondary monitor this behavior does not happen the same as when I am only with one monitor. I even reinstalled swaywm to verify that it was not a waybar error, in swaywm it works correctly even with two monitors.
![error](https://i.ibb.co/qDXMc5s/screen-1638569895.png)

**Comment by jbuchermn** [comment] 2021-12-03 23:33
Is nm-applet the thing on the bottom left of the right screen? And I assume it should be further to the right?

Can you please post a link (or the file) of a waybar config, where this happens. I don't really use waybar and don't have a config that opens nm-applet.

**Comment by CRAG666** [comment] 2021-12-04 17:49
```json
{
    "layer": "bottom",
    "position": "bottom",
    "height": 10,
    "modules-left": ["cpu", "memory", "temperature"],
    "modules-center": ["custom/media"],
    "modules-right": ["network", "tray", "pulseaudio", "backlight", "battery", "clock"],
    "tray": {
        "icon-size": 16,
        "spacing": 10
    },
    "clock": {
        "tooltip-format": "{:%d-%m-%Y | %H:%M}",
        "format-alt": "{:%Y-%m-%d}"
    },
    "cpu": {
        "format": "{usage}% "
    },
    "memory": {
        "format": "{}% ",
        "on-click": "kitty htop"
    },
    "temperature": {
        "critical-threshold": 80,
        "format": "{temperatureC}°C "
    },
    "backlight": {
        "format": "{percent}% {icon}",
        "states": [0,50],
        "format-icons": ["", ""]
    },
    "battery": {
        "states": {
            "good": 95,
            "warning": 30,
            "critical": 15
        },
        "format": "{capacity}% {icon}",
        "format-icons": ["", "", "", "", ""]
    },
    "network": {
        "format-wifi": "{essid}({signalStrength}%)",
        "format-ethernet": "{ifname}: {ipaddr}/{cidr} ",
        "format-disconnected": "Disconnected ⚠",
        "interval" : 7,
        "on-click": "kitty nmtui"

    },
    "pulseaudio": {
        "format": "{volume}% 墳",
        "format-bluetooth": "{volume}% {icon}",
        "format-muted": "婢",
        "format-icons": {
            "headphones": "",
            "handsfree": "",
            "headset": "",
            "phone": "",
            "portable": "",
            "car": "",
            "default": ["", ""]
        },
        "on-click": "pavucontrol"
    }
}
```

**Comment by jbuchermn** [comment] 2021-12-04 23:16
Is this the relevant line?

```
"on-click": "kitty nmtui"
```

Unfortunately I don't use (and don't intend to use) NetworkManager, so it's a bit harder to reproduce for me. Can you find an example, where this bug occurs, without NetworkManager, e.g. "kitty htop"?

**Comment by jbuchermn** [comment] 2021-12-04 23:24
Can you post a picture of what it looks like with only one monitor?

**Comment by jbuchermn** [comment] 2021-12-04 23:42
Nevermind - I found a bug converning xdg-positioner: https://github.com/jbuchermn/pywm/commit/20e5627a68be413639b78162b2484c78abc7de2e

Please open another issue if the bug persists - this is really unrelated to the initial question.

Closing therefore.

**Closed by jbuchermn** 2021-12-04 23:42 UTC
Labels: bug, enhancement
