### ISSUE TITLE
Error making: newm-git 

### ISSUE THREAD

**Issue by Yoliani** [jbuchermn/newm#71] opened 2022-02-26 17:22 UTC
File "/home/edgardoyoliani/.cache/yay/newm-git/src/pywm/setup.py", line 15, in <module>
    raise Exception("Fatal: Error executing 'ninja -C build': \n%r\n%r" % (stdout, stderr))
Exception: Fatal: Error executing 'ninja -C build': 

==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: newm-git

I can't install it with yay -S newm-git

![image](https://user-images.githubusercontent.com/70610879/155852817-695b5b38-de8c-4b0c-af64-f683a6fd4381.png)

![image](https://user-images.githubusercontent.com/70610879/155852759-2fc2e8c7-3aaf-4034-8f93-c88d1e07d47e.png)

**Comment by sadrach-cl** [comment] 2022-02-26 18:45
same error

**Comment by CRAG666** [comment] 2022-02-27 00:00
try this:

The installation in arch is quite simple, I will show you how to install newm v3:

1.- clone the arch repository that we do with yay -G newm-git
2.- cd to the folder we downloaded in the previous step
3.- clone the newm and pywm repositories (git clone https://github.com/jbuchermn/newm.git --branch=v0.3)
4. - in the root of the newm-git folder, type makepkg -sic
5.- run the command newm-cmd clean, if the command works without python errors then you can use newm, otherwise install the missing packages.

**Comment by CRAG666** [comment] 2022-02-27 00:02
https://drive.google.com/file/d/1vjesLnYWbH40U0uAIOmWRfcLRLbHPzE6/view?usp=sharing
the link I share has the newest build of newm

**Comment by sadrach-cl** [comment] 2022-02-27 00:43
> prueba esto:
> 
> La instalación en arch es bastante sencilla, te mostraré como instalar newm v3:
> 
> 1.- clonar el repositorio arch que hacemos con yay -G newm-git 2.- cd a la carpeta que descargamos en el paso anterior 3.- clonar los repositorios newm y pywm (git clone [https://github.com/jbuchermn/newm.git ](https://github.com/jbuchermn/newm.git)--rama=v0.3) 4. - en la raíz de la carpeta newm-git, escriba makepkg -sic 5.- ejecute el comando newm-cmd clean, si el comando funciona sin errores de python entonces puede usar newm, de lo contrario instale los paquetes faltantes.


❯ newm-cmd clean
Traceback (most recent call last):
  File "/usr/bin/newm-cmd", line 3, in <module>
    from newm import cmd
  File "/usr/lib/python3.10/site-packages/newm/__init__.py", line 3, in <module>
    from .run import run
  File "/usr/lib/python3.10/site-packages/newm/run.py", line 12, in <module>
    from .layout import Layout
  File "/usr/lib/python3.10/site-packages/newm/layout.py", line 31, in <module>
    from .dbus import DBusEndpoint, DBusGestureProvider
  File "/usr/lib/python3.10/site-packages/newm/dbus/__init__.py", line 1, in <module>
    from .endpoint import DBusEndpoint
  File "/usr/lib/python3.10/site-packages/newm/dbus/endpoint.py", line 7, in <module>
    from dasbus.loop import EventLoop  # type: ignore
ModuleNotFoundError: No module named 'dasbus'

**Comment by Yoliani** [comment] 2022-02-27 01:38
> try this:
> 
> The installation in arch is quite simple, I will show you how to install newm v3:
> 
> 1.- clone the arch repository that we do with yay -G newm-git 2.- cd to the folder we downloaded in the previous step 3.- clone the newm and pywm repositories (git clone https://github.com/jbuchermn/newm.git --branch=v0.3) 4. - in the root of the newm-git folder, type makepkg -sic 5.- run the command newm-cmd clean, if the command works without python errors then you can use newm, otherwise install the missing packages.


The problem persists

![image](https://user-images.githubusercontent.com/70610879/155864745-ddc53884-cb04-4b9e-aaff-c408a99deaa1.png)

**Comment by CRAG666** [comment] 2022-02-27 02:25
> > try this:
> 
> > The installation in arch is quite simple, I will show you how to install newm v3:
> 
> > 1.- clone the arch repository that we do with yay -G newm-git
> > 2.- cd to the folder we downloaded in the previous step
> > 3.- clone the newm and pywm repositories (git clone https://github.com/jbuchermn/newm.git --branch=v0.3)
> > 4. - in the root of the newm-git folder, type makepkg -sic
> > 5.- run the command newm-cmd clean, if the command works without python errors then you can use newm, otherwise >install the missing packages.
> 
> ❯ newm-cmd clean Traceback (most recent call last): File "/usr/bin/newm-cmd", line 3, in from newm import cmd File "/usr/lib/python3.10/site-packages/newm/**init**.py", line 3, in from .run import run File "/usr/lib/python3.10/site-packages/newm/run.py", line 12, in from .layout import Layout File "/usr/lib/python3.10/site-packages/newm/layout.py", line 31, in from .dbus import DBusEndpoint, DBusGestureProvider File "/usr/lib/python3.10/site-packages/newm/dbus/**init**.py", line 1, in from .endpoint import DBusEndpoint File "/usr/lib/python3.10/site-packages/newm/dbus/endpoint.py", line 7, in from dasbus.loop import EventLoop # type: ignore ModuleNotFoundError: No module named 'dasbus'

Just install the missing dependencies

**Comment by CRAG666** [comment] 2022-02-27 02:32
> > try this:
> > The installation in arch is quite simple, I will show you how to install newm v3:
> > 1.- clone the arch repository that we do with yay -G newm-git 2.- cd to the folder we downloaded in the previous step 3.- clone the newm and pywm repositories (git clone https://github.com/jbuchermn/newm.git --branch=v0.3) 4. - in the root of the newm-git folder, type makepkg -sic 5.- run the command newm-cmd clean, if the command works without python errors then you can use newm, otherwise install the missing packages.
> 
> The problem persists
> 
> ![image](https://user-images.githubusercontent.com/70610879/155864745-ddc53884-cb04-4b9e-aaff-c408a99deaa1.png)

intall ninja:
yay -S ninja

**Comment by sadrach-cl** [comment] 2022-02-27 02:35
❯ newm-cmd clean
Traceback (most recent call last):
  File "/usr/bin/newm-cmd", line 4, in <module>
    __import__('pkg_resources').run_script('newm==0.2', 'newm-cmd')
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.10/site-packages/newm-0.2-py3.10.egg/EGG-INFO/scripts/newm-cmd", line 3, in <module>
    from newm import cmd
  File "/usr/lib/python3.10/site-packages/newm-0.2-py3.10.egg/newm/__init__.py", line 9, in <module>
    from .run import run
  File "/usr/lib/python3.10/site-packages/newm-0.2-py3.10.egg/newm/run.py", line 5, in <module>
    from .layout import Layout
  File "/usr/lib/python3.10/site-packages/newm-0.2-py3.10.egg/newm/layout.py", line 22, in <module>
    from pywm.touchpad import (
ModuleNotFoundError: No module named 'pywm.touchpad'

> @sadrach-cl @Yoliani @Pandademic The error is nothing more than not all the dependencies were specified in the pkbuild, install ninja and the problem is solved

**Comment by Yoliani** [comment] 2022-02-27 02:44
> @sadrach-cl @Yoliani @Pandademic The error is nothing more than not all the dependencies were specified in the pkbuild, install ninja and the problem is solved

All dependencies are installed, but the error persists

**Comment by CRAG666** [comment] 2022-02-27 02:51
install these, this is a dependency error. It was my mistake not to write down the dependencies that I installed when I compiled the program

**Comment by CRAG666** [comment] 2022-02-27 02:55
ok, there is an error when compiling forget all the above, well what you can do is use the file that I built I left the link in the first messages

**Comment by sadrach-cl** [comment] 2022-02-27 02:59
I deleted and cleaned everything, reinstalled the dependencies (I already had all of them, including the ones in your last list). I followed the indications that you published here step by step and the error is the same as at the beginning.
![2022-02-26T23:58:40,836144007-03:00](https://user-images.githubusercontent.com/11355211/155866375-d846bc1b-b0be-4add-bf0e-ff876c3a49c8.png)

**Comment by CRAG666** [comment] 2022-02-27 03:04
@sadrach-cl I could use a previous version of ninja, it is to test the problem I am sure it was some update of ninja or meson

**Comment by sadrach-cl** [comment] 2022-02-27 03:07
Meson --version 
0.61.2
Ninja --version
1.10.2

**Comment by CRAG666** [comment] 2022-02-27 03:16
It is very strange that this happened literally 8 days ago compile newm and the error did not appear, it is not meson, nor ninja the problem I already downgraded both and the problem persists, the error could be somewhere else, I will try to compile some other package that to track down the problem

**Comment by sadrach-cl** [comment] 2022-02-27 03:22
It's okay, it can happen.
 I'm interested in testing the project so when you find the solution let me know here to test it.
 
 saludos, bro.

**Comment by CRAG666** [comment] 2022-02-27 04:24
In the video I show how I install and solve the error

**Comment by sadrach-cl** [comment] 2022-02-27 20:48
ok, the process finishes without errors, but it does not copy the files to "/usr/bin" nor to "~/.local/lib/python3.10/site-packages/". 

the log throws the following:

cat .cache/newm_log
Traceback (most recent call last):
  File "/usr/bin/.start-newm", line 5, in <module>
    from newm import run
  File "/home/sadrach/.local/lib/python3.10/site-packages/newm/__init__.py", line 3, in <module>
    from .run import run
  File "/home/sadrach/.local/lib/python3.10/site-packages/newm/run.py", line 12, in <module>
    from .layout import Layout
  File "/home/sadrach/.local/lib/python3.10/site-packages/newm/layout.py", line 11, in <module>
    from pywm import (
ModuleNotFoundError: No module named 'pywm'

**Comment by Pandademic** [comment] 2022-02-27 21:23
> @sadrach-cl @Yoliani @Pandademic The error is nothing more than not all the dependencies were specified in the pkbuild, install ninja and the problem is solved

@CRAG666 has anyone tried getting the deps. by `pip`?

**Comment by Narcha** [comment] 2022-02-27 21:50
The build fails in `subprojects/wlroots/examples/dmabuf-capture.p/dmabuf-capture.c.o `.
Looking into this, it seems like [this](https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3377) is the root cause.
They merged a fix 6 days ago.

**Comment by jbuchermn** [comment] 2022-02-28 16:43
Hi all,

thanks a lot for debugging this and pointing me to the wlroots bug.

I just updated pywm v0.3 - can you try if installation on branches v0.3 works? master is not updated and I'll probably not bother with doing so and instead merge v0.3 a bit earlier.

**Comment by jbuchermn** [comment] 2022-02-28 16:58
Also, I changed the AUR package to use unstable (v0.3), but I'm not running Arch at the moment so I cannot test if that actually works. If you could give me some feedback, that's greatly appreciated.

**Comment by Narcha** [comment] 2022-02-28 17:04
on it.

**Comment by Narcha** [comment] 2022-02-28 17:13
For me, `yay -S newm-git` still fails with the same error. Is v0.3 using a fixed wlroots version?
See [stderr of `yay -S newm-git`](https://github.com/jbuchermn/newm/files/8155268/newm-err.txt)

**Comment by sadrach-cl** [comment] 2022-02-28 17:16
> For me, `yay -S newm-git` still fails with the same error. Is v0.3 using a fixed wlroots version? See [stderr of `yay -S newm-git`](https://github.com/jbuchermn/newm/files/8155268/newm-err.txt)

I used this method, not with yay.


1.- clone the arch repository that we do with yay -G newm-git
2.- cd to the folder we downloaded in the previous step
3.- clone the newm and pywm repositories (git clone https://github.com/jbuchermn/newm.git --branch=v0.3)
4. - in the root of the newm-git folder, type makepkg -sic

**Comment by Narcha** [comment] 2022-02-28 17:17
I cleared yay's cache and rebuilt, now it works. Thanks for the speedy fix!

**Comment by CRAG666** [comment] 2022-03-01 15:19
@sadrach-cl @Yoliani @Pandademic Now it is patched, you should be able to install newm without problems.

**Comment by CRAG666** [comment] 2022-03-01 15:21
> > For me, `yay -S newm-git` still fails with the same error. Is v0.3 using a fixed wlroots version? See [stderr of `yay -S newm-git`](https://github.com/jbuchermn/newm/files/8155268/newm-err.txt)
> 
> I used this method, not with yay.
> 
> 1.- clone the arch repository that we do with yay -G newm-git 2.- cd to the folder we downloaded in the previous step 3.- clone the newm and pywm repositories (git clone https://github.com/jbuchermn/newm.git --branch=v0.3) 4. - in the root of the newm-git folder, type makepkg -sic

This is already working, v3 is patched. It only remains to install all the dependencies, because as I said the pkbuild does not contain all the dependencies for v3.

**Comment by Yoliani** [comment] 2022-03-01 15:52
> @sadrach-cl @Yoliani @Pandademic Now it is patched, you should be able to install newm without problems.

![image](https://user-images.githubusercontent.com/70610879/156201919-8b4533a6-270e-4e5b-98aa-4f6fc1516c36.png)

**Comment by CRAG666** [comment] 2022-03-01 16:52
> > @sadrach-cl @Yoliani @Pandademic Now it is patched, you should be able to install newm without problems.
> 
> ![image](https://user-images.githubusercontent.com/70610879/156201919-8b4533a6-270e-4e5b-98aa-4f6fc1516c36.png)

yay -S python-dasbus

**Comment by jbuchermn** [comment] 2022-03-01 17:57
> > > For me, `yay -S newm-git` still fails with the same error. Is v0.3 using a fixed wlroots version? See [stderr of `yay -S newm-git`](https://github.com/jbuchermn/newm/files/8155268/newm-err.txt)
> 
> > 
> 
> > I used this method, not with yay.
> 
> > 
> 
> > 1.- clone the arch repository that we do with yay -G newm-git 2.- cd to the folder we downloaded in the previous step 3.- clone the newm and pywm repositories (git clone https://github.com/jbuchermn/newm.git --branch=v0.3) 4. - in the root of the newm-git folder, type makepkg -sic
> 
> 
> 
> This is already working, v3 is patched. It only remains to install all the dependencies, because as I said the pkbuild does not contain all the dependencies for v3.

Are there other dependencies missing apart from dasbus? Will add them as soon as possible.

**Comment by sadrach-cl** [comment] 2022-03-01 20:05
pip3 install python-Levenshtein

**Comment by Pandademic** [comment] 2022-03-01 20:23
@CRAG666 I agree with you , a requirments.txt is necessary.

**Comment by jbuchermn** [comment] 2022-03-01 20:40
> pip3 install python-Levenshtein

Are you sure on this one? Never even heard of that library. Maybe this is pulled in by some dependency, but I'd be very surprised if it had to be added manually to newm.

I just checked the Python dependencies and I'm pretty sure they're completely listed in `flake.nix` (in the end, it runs on nixOS, which it wouldn't if there were any dependencies missing). The same dependencies should be in the AUR (I just checked and the latest commit contains `python-dasbus`).

I wasn't really talking about Python dependencies, rather about non-Python ones (on the AUR). AAMOF, `ninja` was missing until the last commit. So if you see anything missing there, please post here.

> @jbuchermn If 2 or 3 are missing, I honestly didn't pay attention to it when I installed v3 for the first time. But it would also help to have a requirements.txt

> @CRAG666 I agree with you , a requirments.txt is necessary.

I'm not so keen on having a requirements.txt, as it's just one more place (next to `setup.py` and `flake.nix`) to keep up-to-date, but yeah, maybe I'll add one and hope it will stay in sync ;)

**Comment by Yoliani** [comment] 2022-03-01 21:13
> > > @sadrach-cl @Yoliani @Pandademic Now it is patched, you should be able to install newm without problems.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/70610879/156201919-8b4533a6-270e-4e5b-98aa-4f6fc1516c36.png)
> 
> Remove the installation you have done with pip and install it with the following command: yay -S python-dasbus
it does not work

**Comment by jbuchermn** [comment] 2022-03-01 21:15
Are you actually inside newm? This complains it can't connect on dbus. It won't work when not run inside newm v0.3

**Comment by CRAG666** [comment] 2022-03-01 21:30
> > > > @sadrach-cl  @Yoliani  @Pandademic Ahora está parcheado, deberías poder instalar newm sin problemas.
> > > 
> > > 
> > > ![imagen](https://user-images.githubusercontent.com/70610879/156201919-8b4533a6-270e-4e5b-98aa-4f6fc1516c36.png)
> > 
> > 
> > Elimina la instalación que has hecho con pip e instálala con el siguiente comando: yay -S python-dasbus 
> > pip desinstalar dasbus 
> > yay -S python-dasbus
> 
> No funciona

@Yoliani run newm and then try the command, it seems that all dependencies have been installed. Then just start newm

**Comment by CRAG666** [comment] 2022-03-01 21:35
> > pip3 instalar python-Levenshtein
> 
> ¿Estás seguro de esto? Ni siquiera he oído hablar de esa biblioteca. Tal vez esto se deba a alguna dependencia, pero me sorprendería mucho si tuviera que agregarse manualmente a newm.
> 
> Acabo de comprobar las dependencias de Python y estoy bastante seguro de que están completamente enumeradas en `flake.nix`(al final, se ejecuta en nixOS, lo que no sucedería si faltaran dependencias). Las mismas dependencias deberían estar en AUR (lo acabo de comprobar y la última confirmación contiene `python-dasbus`).
> 
> Realmente no estaba hablando de las dependencias de Python, sino de las que no son de Python (en AUR). AAMOF, `ninja`faltaba hasta la última confirmación. Entonces, si ve que falta algo allí, publíquelo aquí.
> 
> > @jbuchermn Si faltan 2 o 3, honestamente no le presté atención cuando instalé v3 por primera vez. Pero también ayudaría tener un requirements.txt
> 
> > @ CRAG666 Estoy de acuerdo con usted, se necesita un requirments.txt.
> 
> No estoy tan interesado en tener un requirements.txt, ya que es solo un lugar más (al lado de `setup.py`y `flake.nix`y PKGBUILD) para mantenerme actualizado, pero sí, tal vez agregue uno y espero que se mantenga sincronizado;)

I understand, could you offer me as the maintainer of that file, also in a while I will upload a pr with the instructions on how to build newm in arch, I just need the name of the current dependencies of newm and that's it. This manual page will be updated as newm grows

**Comment by sadrach-cl** [comment] 2022-03-02 00:09
> 
> > pip3 install python-Levenshtein
> 
> Are you sure on this one? Never even heard of that library. Maybe this is pulled in by some dependency, but I'd be very surprised if it had to be added manually to newm.
> 
yesterday i got an error when i tried to boot and it indicated that something was deprecated. it suggested installing that package to fix it. i tried to look in the logs, but they were stepped on with today's logs.

**Comment by sadrach-cl** [comment] 2022-03-02 00:29
yes, I am already cooking rice
![20220301_21h27m08s_grim](https://user-images.githubusercontent.com/11355211/156271684-1baa0199-bfbd-449c-90d2-c5941d7bc32e.png)

**Comment by CRAG666** [comment] 2022-03-02 00:57
> yes, I am already cooking rice ![20220301_21h27m08s_grim](https://user-images.githubusercontent.com/11355211/156271684-1baa0199-bfbd-449c-90d2-c5941d7bc32e.png)

https://github.com/CRAG666/dotfiles
welcome to newm, I leave you my dotfiles maybe they will be useful to you

**Comment by jbuchermn** [comment] 2022-03-02 09:14
> > > pip3 install python-Levenshtein
> > 
> > 
> > Are you sure on this one? Never even heard of that library. Maybe this is pulled in by some dependency, but I'd be very surprised if it had to be added manually to newm.
> 
> yesterday i got an error when i tried to boot and it indicated that something was deprecated. it suggested installing that package to fix it. i tried to look in the logs, but they were stepped on with today's logs.

Ah that's quite interesting.. Maybe has got something to do with fuzzywuzzy (https://pypi.org/project/fuzzywuzzy/) - the dependency is listed there. fuzzywuzzy appears to be deprecated completely, so I'll change this to its successor. https://github.com/jbuchermn/newm/issues/76

**Comment by Pandademic** [comment] 2022-03-02 20:32
@sadrach-cl WOW 😲! Please send config's later. They'll definitely be useful in future reference , at least for ricing NEWM

**Comment by Pandademic** [comment] 2022-03-02 20:33
@jbuchermn is `requirements.txt` up to date now? If not , I'll send a PR

**Comment by jbuchermn** [comment] 2022-03-02 20:46
Yes, only pywm is not listed, as it's not distributed on pypi. But pywms requirements.txt is also up-to-date (in both cases on branch v0.3)

**Comment by sadrach-cl** [comment] 2022-03-02 21:50
I don't want to open a new issue for this. Any telegram, discord or reddit group to follow? there are simple things to ask and a community helps a lot more than filling the issues repository. 

 Now, how can I solve the rounded saw corners and increase the speed when pressing commands like "logo+HJKL"?

**Comment by Pandademic** [comment] 2022-03-03 20:56
@jbuchermn maybe gitter?

**Comment by jbuchermn** [comment] 2022-03-07 20:38
I created a gitter community: https://gitter.im/jbuchermn-newm/community# Let's see if this works, I've never used that before.

Closing this issue for now, as it's become about something else.

**Closed by jbuchermn** 2022-03-07 20:38 UTC
Labels: documentation

**Comment by lidgnulinux** [comment] 2022-05-14 00:38
If you all are facing "avcodec" error while building or installing pywm and newm, you need to try relinking libavcodec and libavcodec.pc to 58 version and not the 59 one.

**Comment by TooSpooky** [comment] 2023-03-22 05:58
Hey, hate to bring this up as the project is no longer maintained but as I mentioned in another issue I seem to have this problem.

Manually installed everything within the requirements.txt's of each pywm and newm. Including Ninja, levenshtein, meson, and dasbus via Yay. I've tried installing via yay -S newm-git and yay -G newm-git

Although I'm new to this so I could be missing something or something said earlier in the thread, just thought i'd leave this here for the future or in-case someone would be kind enough to give me a hand to try it out.

Thanks for your time.

<img width="430" alt="vmplayer_VAIJuuPGhW" src="https://user-images.githubusercontent.com/21211292/226814270-82a64892-8370-4af5-a656-d47a84277ea8.png">

**Comment by tewkanz** [comment] 2023-03-28 23:49
pywm is built using a specific revision of wlroots, but it sounds like maybe that doesn't play nice with some of the dependencies of wlroots being on a newer version (just guessing since some of the errors mention deprecation). This isn't a problem when we build newm on nix, I guess because nix gets the correct version of the dependencies as well?

You might be able to try either overriding wlroots to ignore warnings during build. In subprojects/wlroots/meson.build, remove the line 'werror=true' [here](https://github.com/swaywm/wlroots/blob/master/meson.build#L10). 

newm might also build okay with wlroots up to date? You could try running git pull from subprojects/wlroots and pulling down a more recent version.

**Comment by TooSpooky** [comment] 2023-04-28 19:48
Hey @Pandademic no problem at all, I just appreciate a reply haha. For sure let me know if you find a fix for wlroots. Would love to give this a shot. 

A lot to ask but i’d also appreciate some more detailed instructions on how to get a basic semi-functional setup, from the standpoint of someone who uses windows usually but thinks newm is interesting and wants to give it a shot in a vm. (I.E. can navigate to files and edit them in nano or whatever but doesn’t know what to put in them or where to input entries in the file, etc) for a distro you find it currently functional on. Once I have a basic working setup I can generally dissect how to edit configs and such to my liking, but before then haha i’m a lil lost. Only if you have the time and it’s no trouble. 

Thanks and take care!

**Comment by Pandademic** [comment] 2023-04-29 00:26
@TooSpooky It's a little late where I am now, I will send you smth about getting a working (functional) vm to play with newm in tommorow.Is there a better place I can send the stuff to you own? Perhaps gitter or discord?

**Comment by TooSpooky** [comment] 2023-04-29 01:39
Thanks man, truly appreciate it. Sure, can send me a dm on discord at TooSpooky#8860. I’ve just been using vmware to mess around with stuff so far, if that makes any difference.

**Comment by Pandademic** [comment] 2023-04-29 12:34
I sent a friend on discord @TooSpooky.

**Comment by TooSpooky** [comment] 2023-04-29 17:33
Accepted, thanks.
