### ISSUE TITLE
Core dump on 0.3

### ISSUE THREAD

**Issue by Pandademic** [jbuchermn/newm#91] opened 2022-03-22 20:44 UTC
`start-newm -d` core dumps from tty after `yay -s` install

**Comment by Pandademic** [comment] 2022-03-23 00:04
@jbuchermn says something about libseat

**Comment by CRAG666** [comment] 2022-03-23 03:40
It is possible that you are missing a package that has already happened to me

**Comment by jbuchermn** [comment] 2022-03-23 07:08
Please post logs, otherwise there's nothing we can do.

BTW, aur has v0.3

**Comment by CRAG666** [comment] 2022-03-23 14:52
As such it doesn't have v3 you can build v3 by modifying the PKBUILD

**Comment by CRAG666** [comment] 2022-03-23 14:54
by the way the the fuzz library is not available in the repositories it has to be installed with pip

**Comment by jbuchermn** [comment] 2022-03-23 19:47
> As such it doesn't have v3 you can build v3 by modifying the PKBUILD

No. Check the PKGBUILD.



> by the way the the fuzz library is not available in the repositories it has to be installed with pip

That's an important piece of information, can you add that to the doc?

**Comment by Pandademic** [comment] 2022-03-23 20:46
@CRAG666 shouldn't libseat be a dependency in the `PKGBUILD`?

**Comment by jbuchermn** [comment] 2022-03-23 21:15
That's a good point, however on nixOS it's not necessary...

There's an easy way to test this - install libseat, try again, does anything change?

**Comment by Pandademic** [comment] 2022-03-23 21:16
@jbuchermn I'll get to that now

**Comment by CRAG666** [comment] 2022-03-23 23:47
> > As such it doesn't have v3 you can build v3 by modifying the PKBUILD
> 
> No. Check the PKGBUILD.
> 
> > by the way the the fuzz library is not available in the repositories it has to be installed with pip
> 
> That's an important piece of information, can you add that to the doc?

Of course I will do a documentation pr

**Comment by Pandademic** [comment] 2022-03-24 20:04
@jbuchermn that doesn't help ...` seatd ` is the package , right?
Also , I get the same error on sway

**Comment by Pandademic** [comment] 2022-03-24 20:55
if I use
`dbus-run-session start-newm -d`
it kinda works....(possible screen freeze)
following sway suggestions helps , i've noticed

**Comment by jbuchermn** [comment] 2022-03-25 13:17
> @jbuchermn that doesn't help ...`seatd` is the package , right? **LOG NOTICINGS:**
> 
> * `brightnessctl` errors untill I manually install it , it should be in the `PKGBUILD` with `seatd` , can I submit a PR?
> * python says `traceback error : ValueError: invalid literal int() with base 10` showing lines 99 and 24 in file helper/backlight_manager.py.Is this a syntax error or just something I did?


`backlight_manager` is an optional dependency, only if you use `BacklightManager`. However this errors should not be fatal, just a lot of log output, but this can't cause the core dump.

Nope, it's nothing you did, probably fixed once brightnessctl is working.

> * the log has a lot of libseat errors and a final failed assertion from pywm/newm
> * **OTHER STUFF:**
>   if I use
>   `dbus-run-session start-newm -d`
>   it kinda works....(possible screen freeze)
>   following sway suggestions helps , i've noticed

It's most certainly related to libseat / seatd. Possible cause could be seatd not running and libseat refusing to use systemd-logind (which is something I've seen in the past on arch linux). If you would post a log, we could tell.

Probably @CRAG666 knows better, how to fix this, as I'm not on arch anymore.

**Comment by Pandademic** [comment] 2022-03-25 19:47
@jbuchermn it's in a VM , I can't get the log.
anyway , 

- sway doesn't start either with the same result as `dbus-run session start-newm -d` , the screen hangs
- "Possible cause could be seatd not running and libseat refusing to use systemd-logind (which is something I've seen in the past on arch linux)." - How did you fix it? I'll try using `elogind`
- you disable `BacklightManager` through the config , right?

**Comment by jbuchermn** [comment] 2022-03-25 19:53
> @jbuchermn it's in a VM , I can't get the log.
> 
> anyway , 
> 
> 
> 
> - sway doesn't start either with the same result as `dbus-run session start-newm -d` , the screen hangs

Okay, probably also a good idea to look for help there as it's a lot bigger of a community.

> - "Possible cause could be seatd not running and libseat refusing to use systemd-logind (which is something I've seen in the past on arch linux)." - How did you fix it? I'll try using `elogind`

Using seatd.

> - you disable `BacklightManager` through the config , right?

Yup, just remove it from your config.

**Comment by Pandademic** [comment] 2022-03-25 20:00
@jbuchermn can you send me a example newm config _without backlight manager_ and i'll try it?

**Comment by jbuchermn** [comment] 2022-03-25 22:47
Just remove it from your config.

But as I said above, that's not the cause of your coredump. It's most certainly a libseat issue.

**Comment by Pandademic** [comment] 2022-03-26 14:28
@jbuchermn yes , but it
s easier to disable for a easier to read 
log

**Comment by CRAG666** [comment] 2022-03-26 22:45
The problem is easier to fix than it seems, it's just a bit tedious. First make sure you have all the dependencies that newm uses installed, don't rely on pkbuild. Second once compiled and installed in a tty section start newm, it is very likely that you use systemd so set the environment variables correctly. You were able to check my dotfiles, I have a folder called waylando where I have a group of scripts to be able to execute any composer in wayland without problems.

**Comment by Pandademic** [comment] 2022-03-27 14:01
@CRAG666 thanks i'll try this on the VM

**Comment by jbuchermn** [comment] 2022-04-01 09:01
> Getting segfaults here after 1-2 minutes of the program being open. A bit of a pattern I've noticed is that normally, an animation is played at some point between animation queues. Whenever there's a segfault, there are two animations queued with no animation played between. I uploaded this part of the log [here](https://pastebin.com/GEpxwKU2).
> 
> 
> 
> Mesa: 21.3.7-2 on Intel Tiger Lake (Xe) Graphics

Thanks for the logs. This however appears to be unrelated to the particular issue here, but a pywm bug triggered by closing windows. I'll open an issue there and take a look.

**Comment by jbuchermn** [comment] 2022-04-18 20:07
Closing this for now.

**Closed** 2022-04-18 20:07 UTC
Labels: documentation
