### ISSUE TITLE
The size established in the floating windows is not respected

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#25] opened 2021-11-15 14:52 UTC
With the new feature of floating windows, everything works fine except, the window size, I set a size of 900x900 and it is not respected.
![pavucontrol not foudn](https://i.ibb.co/z2sXPY0/screen-1636987775.png)

**Comment by jbuchermn** [comment] 2021-11-15 14:59
Okay, this looks like a bug. I only tested the feature with a couple of apps, not pavucontrol.

**Comment by CRAG666** [comment] 2021-11-15 15:02
the same thing happens with blueman-manager

**Comment by jbuchermn** [comment] 2021-11-15 15:44
see https://github.com/jbuchermn/newm/commit/34ab2f8eb164ea2ecbbed3d0a33f1fcd1f271768

**Comment by CRAG666** [comment] 2021-11-15 19:21
Everything works fine, but I notice that when Modpress the floating window takes a larger size, in particular it doesn't bother me, but I don't know if that behavior is part of the design
![its working](https://i.ibb.co/kcZ0hwK/screen-1637003479.png)
![Modpress](https://i.ibb.co/ss76skX/screen-1637003485.png)

**Comment by jbuchermn** [comment] 2021-11-15 22:05
Good catch, that's actually a regression introduced by recent changes. Should be fixed by https://github.com/jbuchermn/newm/commit/99ceb5c9236dab80af61e67873f484bc79300f7b

**Comment by CRAG666** [comment] 2021-11-16 00:50
it's Working

**Closed** 2021-11-16 00:50 UTC
Labels: bug
