### ISSUE TITLE
Black screen, cant open alacritty

### ISSUE THREAD

**Issue by e-mm-a** [jbuchermn/newm#5] opened 2021-11-04 00:40 UTC
When running newm, i just get a black screen, and `Logo+Enter` does nothing. If i try to run
```sh
WAYLAND_DISPLAY="wayland-0" alacritty
```
from `tty2` it doesnt error, but it also doesnt show up in newm. From what I understand, the logs show it creates the window, but its not displayed. I'm not sure if this is relevant, but im running it as
```sh
cd path/to/newm
PATH="$PATH:." python -u -c "from newmimport run; run()"
```
as i have newm installed in a venv. 

Also not sure if relevant, but logs are inconsistent (sometimes errors from wlroots etc) and each time i get
```py
[WARNING] layout.py:820 ...: Unexpected: View <View 3 (root): Alacritty, Alacritty, toplevel, 20593, xwayland=False, floating=false> state not found
```

**Comment by jbuchermn** [comment] 2021-11-04 09:49
I'm not quite sure what's happening here. The "Unexpected" logs can indicate an issue, but should not cause a black screen... So I think there's something else going wrong here. Can you post the full log file and your config?

**Comment by jbuchermn** [comment] 2021-11-04 09:52
And, just as a sanity check.. does sway start up without issue?

**Comment by e-mm-a** [comment] 2021-11-04 11:56
Sway works fine. My config is just the `default_config.py` copied to `~/.config/newm/config.py` (but I had the same issue with no config file).
And heres the log. I did `Logo+Enter`, then i opened an alacritty from `tty2`. The crash at the end is just because I did `pkill python`.
https://gist.github.com/e-mm-a/bcbbb0b1217df97015f6cfaea25bba6d

**Comment by jbuchermn** [comment] 2021-11-04 12:12
Thanks for the log. I can see what went wrong; I just pushed a fix to pywm. Can you try?

**Comment by e-mm-a** [comment] 2021-11-04 12:22
Different error now (I think). Hopefully I managed to update pywm correctly.
https://gist.github.com/e-mm-a/184b44dbcf6947a59155fd51854bb23e

**Comment by jbuchermn** [comment] 2021-11-04 14:59
Hmm. this actually looks exactly like the error I was getting before the latest commit. Can you check that you are on the latest commit (0c3c119555ecae8888 of pywm)? You need to re-run setup.py which should run meson in the background, as the change is in c code

Btw, the issue is this line:

```
[DEBUG] pywm.py:258 2021-11-04 12:15:41: PyWM layout change: 0x0
```

newm does not get correct information about the display dimensions from pywm and places every window with size 0 by 0.

**Comment by e-mm-a** [comment] 2021-11-04 15:45
Ah sorry about that, I didnt update it properly. Making a new venv fixed it. Alacritty is opening now, but trackpad gestures arent. Do you want me to open a new issue?

**Comment by jbuchermn** [comment] 2021-11-04 15:50
That's great to hear! Can you open a new issue? I have a feeling that others will report issues concerning setting up the trackpad, so probably that's easier to find.

**Closed by jbuchermn** 2021-11-04 15:50 UTC
